#!/bin/bash

hc() { herbstclient "$@" ;}

Mod=Mod4
feh --no-fehbg --bg-center ~/.config/herbstluftwm/wallpaper.png

modbind() {
    keys=$1
    shift 1
    hc keybind Mod4-$keys "$@"
    hc keybind Ctrl-Alt-$keys "$@"
}

# colors
hc set frame_border_active_color '#afdf5f'
hc set frame_border_normal_color '#afdf87'
hc set frame_bg_normal_color '#00aaee'
hc set frame_bg_active_color '#00aaee'
#hc set frame_active_opacity 40
#hc set frame_normal_opacity 20
hc set frame_bg_transparent 1
hc set window_border_normal_color '#afafdf'
hc set window_border_active_color '#df8787'

# Look
hc set always_show_frame 0
hc set gapless_grid 0
hc set default_frame_layout 3
hc set focus_follows_mouse 1
hc set raise_on_focus 0
hc set raise_on_click 1
hc set smart_frame_surroundings 1
hc set smart_window_borders 1
hc set tree_style '╾│ ├╰╼─╮'
hc set swap_monitors_to_get_tag 0
hc set frame_transparent_width 0

# Rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off # Don't manage docks and notifications
hc rule class=Cellwriter manage=off # Don't manage cellwriter
hc rule class=Onboard manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on # Pseudotile dialogs and splashes
hc rule windowrole=GtkFileChooserDialog pseudotile=off # Don't pseudotile file chooser dialogs

# Settings which draw to the screen finished
hc unlock

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}"
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        modbind "$key" use_index "$i"
        modbind "Shift-$key" move_index "$i"
    fi
done


# Autorun
[[ -z "$HLWM_LOADED" ]] && ~/.config/herbstluftwm/autorun &

# keybindings
modbind Shift-q quit
modbind Shift-r reload
modbind Shift-c close
modbind Return spawn urxvtcd
modbind d spawn bash -c 'dmenu-launch'
modbind d spawn bash -c 'DMENU_OPTIONS="-nf #d0d0d0 -nb #4e4e4e -sf #b2b2b2 -sb #3a3a3a" dmenu-launch'

# layouting
modbind r remove
modbind space cycle_layout 1
modbind u split vertical 0.5
modbind o split horizontal 0.5
modbind s floating toggle
modbind f fullscreen toggle
modbind p pseudotile toggle

# resizing
RESIZESTEP=0.05
modbind Control-h resize left +$RESIZESTEP
modbind Control-j resize down +$RESIZESTEP
modbind Control-k resize up +$RESIZESTEP
modbind Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
modbind t raise
modbind BackSpace   cycle_monitor
modbind Tab         cycle_all +1
modbind Shift-Tab   cycle_all -1
modbind c cycle
modbind h focus left
modbind j focus down
modbind k focus up
modbind l focus right
modbind Shift-h shift left
modbind Shift-j shift down
modbind Shift-k shift up
modbind Shift-l shift right
modbind w spawn ~/bin/wselect

# Volume keys
hc keybind XF86AudioLowerVolume spawn ~/bin/volume decrease
hc keybind XF86AudioRaiseVolume spawn ~/bin/volume increase
hc keybind XF86AudioMute spawn ~/bin/volume mute

# Rotate key
# since some update, this suddenly gets mapped to the wrong key, wtf.
hc keybind XF86RotateWindows spawn ~/bin/xrotate toggle
hc keybind XF86TaskPane spawn ~/bin/xrotate toggle

# Thinkpad back/forward keys
hc keybind Shift-XF86Back spawn ~/bin/tagswitch prev
hc keybind Shift-XF86Forward spawn ~/bin/tagswitch next
hc keybind XF86Back use_index -1
hc keybind XF86Forward use_index +1

# Fn + F4
hc keybind XF86ScreenSaver chain , spawn xset dpms force off , spawn physlock -s

# ThinkVantage-Key
hc keybind XF86Launch1 spawn urxvtcd
hc keybind XF86Launch2 spawn ~/bin/onboardctl toggle

# utf8select
modbind y spawn ~/bin/utf8select

# Fix java
hc setenv _JAVA_AWT_WM_NONREPARENTING 1

# Xojtex
modbind t spawn ~/bin/xojtex

# Fix xdg-open
hc setenv DE gnome
hc setenv BROWSER chromium

# No beeps
xset -b

# Avoid autostart being executed twice
hc setenv HLWM_LOADED 1
