#!/bin/bash

hc() { herbstclient "$@" ;}

Mod=Mod4
feh --no-fehbg --bg-center ~/.config/herbstluftwm/wallpaper.png

# colors
hc set frame_border_active_color '#afdf5f'
hc set frame_border_normal_color '#afdf87'
hc set frame_bg_normal_color '#00aaee'
hc set frame_bg_active_color '#00aaee'
#hc set frame_active_opacity 40
#hc set frame_normal_opacity 20
hc set frame_bg_transparent 1
hc set window_border_normal_color '#afafdf'
hc set window_border_active_color '#df8787'

# Look
hc set always_show_frame 0
hc set gapless_grid 0
hc set default_frame_layout 3
hc set focus_follows_mouse 1
hc set raise_on_focus 0
hc set raise_on_click 1
hc set smart_frame_surroundings 1
hc set smart_window_borders 1
hc set tree_style '╾│ ├╰╼─╮'
hc set swap_monitors_to_get_tag 0
hc set frame_transparent_width 0

# Rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off # Don't manage docks and notifications
hc rule class=Cellwriter manage=off # Don't manage cellwriter
hc rule class=Onboard manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on # Pseudotile dialogs and splashes
hc rule windowrole=GtkFileChooserDialog pseudotile=off # Don't pseudotile file chooser dialogs

# Settings which draw to the screen finished
hc unlock

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}"
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# Autorun
[[ -z "$HLWM_LOADED" ]] && ~/.config/herbstluftwm/autorun &

# keybindings
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvtcd
hc keybind $Mod-d spawn bash -c 'dmenu-launch'
hc keybind $Mod-d spawn bash -c 'DMENU_OPTIONS="-nf #d0d0d0 -nb #4e4e4e -sf #b2b2b2 -sb #3a3a3a" dmenu-launch'

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

# mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-t raise
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# Volume keys
hc keybind XF86AudioLowerVolume spawn ~/bin/volume decrease
hc keybind XF86AudioRaiseVolume spawn ~/bin/volume increase
hc keybind XF86AudioMute spawn ~/bin/volume mute

# Rotate key
# since some update, this suddenly gets mapped to the wrong key, wtf.
hc keybind XF86RotateWindows spawn ~/bin/xrotate toggle
hc keybind XF86TaskPane spawn ~/bin/xrotate toggle

# Thinkpad back/forward keys
hc keybind Shift-XF86Back spawn ~/bin/tagswitch prev
hc keybind Shift-XF86Forward spawn ~/bin/tagswitch next
hc keybind XF86Back use_index -1
hc keybind XF86Forward use_index +1

# Fn + F4
hc keybind XF86ScreenSaver chain , spawn xset dpms force off , spawn xscreensaver-command -lock

# ThinkVantage-Key
hc keybind XF86Launch1 spawn urxvtcd
hc keybind XF86Launch2 spawn ~/bin/onboardctl toggle

# utf8select
hc keybind Mod4-y spawn ~/bin/utf8select

# Fix java
hc setenv _JAVA_AWT_WM_NONREPARENTING 1

# Xojtex
hc keybind Mod4-t spawn ~/bin/xojtex

# Fix xdg-open
hc setenv DE gnome
hc setenv BROWSER chromium

# No beeps
xset -b

# Avoid autostart being executed twice
hc setenv HLWM_LOADED 1
